name = "flags-of-the-world"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
account_id = "6bea4abeca519658cb8ba205c96c1f70"

[durable_objects]
bindings = [
  { name = "GAME_ROOM", class_name = "GameRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["GameRoom"]

[[kv_namespaces]]
binding = "FLAGS_KV"
id = "1760de5884cb4fbb81db4190e3d8a102"
preview_id = "29229cd09ba5498fb3216992cb3242a9"

[vars]
ENVIRONMENT = "production"
