export const COUNTRY_FACTS: Record<string, string> = {
  // ── Africa ────────────────────────────────────────────────────────
  dz: "Algeria is Africa's largest country by area, and the Sahara Desert covers about 90% of its land.",
  ao: "Angola has one of the world's youngest populations — over 65% of its people are under 25.",
  bj: "Benin is considered the birthplace of the Vodun (Voodoo) religion, still practiced by roughly 17% of the population.",
  bw: "Botswana's Okavango Delta is one of the world's largest inland deltas — it floods every year from rain that falls thousands of kilometres away in Angola.",
  bf: "Burkina Faso literally means 'Land of Honest People.' President Thomas Sankara coined the name in 1984 by combining two local languages.",
  bi: "Burundi is one of the few countries in the world where drumming — the Karyenda Royal Drums — is a UNESCO Intangible Cultural Heritage.",
  cv: "Cape Verde was completely uninhabited when Portuguese explorers arrived in 1456, making it one of the last places on Earth settled by humans.",
  cm: "Cameroon is called 'Africa in miniature' because it contains almost every climate and terrain type found on the entire continent.",
  cf: "The Central African Republic is home to the Dzanga-Sangha rainforest, one of the last places on Earth where forest elephants and western lowland gorillas coexist.",
  td: "Lake Chad has shrunk by about 90% since the 1960s due to climate change and irrigation — it once covered an area the size of the United States' Lake Erie.",
  km: "The Comoros islands produce more ylang-ylang per square kilometre than anywhere else on Earth — the flower used in Chanel No. 5 perfume.",
  cg: "The Republic of the Congo borders the world's second-largest tropical rainforest, the Congo Basin, which absorbs vast amounts of the world's carbon dioxide.",
  cd: "The DR Congo's Congo River is the world's deepest river, reaching depths of over 220 metres, and runs so fast it acts as a natural barrier between primate species.",
  dj: "Djibouti hosts military bases from the US, France, China, Japan, and Italy — it's one of the most militarily crowded small nations on Earth.",
  eg: "Egypt's Great Pyramid of Giza is the only surviving ancient Wonder of the World and was the world's tallest man-made structure for over 3,800 years.",
  gq: "Equatorial Guinea is the only African country where Spanish is an official language — a legacy of Spanish colonialism in the 19th century.",
  er: "Eritrea has a rich underwater archaeology — shipwrecks from ancient Aksumite, Ottoman, and colonial-era vessels sit on its Red Sea floor.",
  sz: "Eswatini (formerly Swaziland) is one of the world's last absolute monarchies, and its King can have up to 15 wives by royal tradition.",
  et: "Ethiopia has its own calendar — it has 13 months and is currently about 7–8 years behind the Gregorian calendar, meaning Ethiopians celebrated the year 2000 in 2007.",
  ga: "Over 85% of Gabon is covered in equatorial rainforest, and it's home to half of Africa's entire forest elephant population.",
  gm: "The Gambia is the smallest country in mainland Africa, almost entirely surrounded by Senegal except for its Atlantic coastline.",
  gh: "Ghana was the first sub-Saharan African country to gain independence from colonial rule, in 1957, led by Kwame Nkrumah.",
  gn: "Guinea holds more than a third of the world's bauxite reserves — the ore used to make aluminium — making it one of the world's most resource-rich nations.",
  gw: "Guinea-Bissau's Bijagós Archipelago is a UNESCO Biosphere Reserve where saltwater hippos roam coastal islands — an extraordinarily rare sight.",
  ci: "Ivory Coast produces about 40% of the world's cocoa supply, making it the backbone of the global chocolate industry.",
  ke: "Kenya's Great Rift Valley is one of geology's most dramatic features, stretching 6,000 km from Syria to Mozambique — and slowly splitting Africa apart.",
  ls: "Lesotho is the only country in the world entirely surrounded by another country (South Africa) and sits entirely above 1,000 metres elevation.",
  lr: "Liberia, founded in 1847 by freed American slaves, was the first republic in Africa and one of the first in the world to have a female president — Ellen Johnson Sirleaf in 2006.",
  ly: "Libya holds Africa's largest proven oil reserves, and more than 90% of its territory is covered by the Sahara Desert.",
  mg: "Madagascar has been isolated for 88 million years, causing over 90% of its wildlife — including 100+ species of lemurs — to exist nowhere else on Earth.",
  mw: "Lake Malawi contains more fish species than any other lake in the world, including over 1,000 species of cichlids — more than all of Europe and North America combined.",
  ml: "Timbuktu, in Mali, was once one of the world's most important centres of Islamic scholarship, housing over 700,000 manuscripts in the 14th century.",
  mr: "Mauritania was one of the last countries in the world to officially abolish slavery — in 1981 — and only criminalised it in 2007.",
  mu: "The dodo bird, now extinct, was native exclusively to Mauritius. The last confirmed sighting was in 1662, just 64 years after Dutch sailors first arrived.",
  ma: "Morocco is the only African country with coastlines on both the Atlantic Ocean and the Mediterranean Sea, giving it a unique strategic position.",
  mz: "Mozambique's flag is the only national flag in the world to feature an AK-47 assault rifle — representing the country's armed struggle for independence.",
  na: "The Namib Desert in Namibia is the world's oldest desert at over 55 million years old, predating even the Sahara by tens of millions of years.",
  ne: "Niger is the largest country in West Africa — about 80% of its territory is covered by the Sahara, making most of the land uninhabitable.",
  ng: "Nigeria is Africa's most populous country with over 220 million people and is home to Nollywood — the world's second-largest film industry by volume, after India.",
  rw: "Rwanda has one of the world's highest percentages of women in parliament — over 60% — and is one of Africa's fastest-growing economies.",
  st: "São Tomé and Príncipe sits almost exactly on the equator and the prime meridian — the geographic centre of the world's coordinate system.",
  sn: "Dakar, Senegal's capital, is the westernmost city in mainland Africa and was historically the final stop of the legendary Paris-Dakar Rally.",
  sc: "Seychelles dedicates more than 50% of its total land area to nature reserves and marine parks — the highest proportion of any country in the world.",
  sl: "Sierra Leone's name means 'Lion Mountains' in Portuguese — a name given by explorer Pedro de Sintra who reportedly heard the roar of thunderstorms in the hills.",
  so: "Somalia has the longest coastline of any country in mainland Africa, stretching over 3,300 km along the Indian Ocean.",
  za: "South Africa is the only country in history to voluntarily develop nuclear weapons and then dismantle them entirely — it destroyed six warheads in the early 1990s.",
  ss: "South Sudan is the world's youngest country, gaining independence from Sudan on 9 July 2011 after a decades-long civil war.",
  sd: "Sudan has more ancient pyramids than Egypt — over 200 Nubian pyramids built by the Kushite kingdoms — but they are far less well known.",
  tz: "Tanzania is home to Mount Kilimanjaro, Africa's highest peak at 5,895 metres, and the Serengeti — host to the world's largest annual animal migration.",
  tg: "Lomé, Togo's capital, is the only capital city in Africa that directly borders another country at its western edge — Ghana.",
  tn: "Tunisia is the northernmost country in Africa and was home to the ancient city of Carthage, once a superpower that fought Rome for control of the Mediterranean.",
  ug: "Uganda is home to roughly half of the world's remaining mountain gorilla population — fewer than 1,100 survive in the wild.",
  zm: "Zambia is home to Victoria Falls — known locally as 'Mosi-oa-Tunya' (The Smoke That Thunders) — which creates its own rainforest microclimate.",
  zw: "The ruins of Great Zimbabwe gave the country its name and were built without mortar around the 11th century — the largest stone structures south of the Sahara.",

  // ── Americas ──────────────────────────────────────────────────────
  ag: "Antigua has 365 beaches — one for every day of the year — most of them white-sand coves protected by coral reefs.",
  ar: "Buenos Aires' Avenida 9 de Julio is the widest avenue in the world, with up to 22 lanes of traffic and the famous Obelisco at its centre.",
  bs: "The Bahamas was the first place Christopher Columbus stepped ashore in the Americas in 1492, and its waters contain the third-largest barrier reef system on Earth.",
  bb: "Barbados is credited as the birthplace of rum — sugarcane was first distilled into 'kill-devil' spirit here in the 1620s.",
  bz: "Belize's Great Blue Hole is a 300-metre-wide, 125-metre-deep underwater sinkhole and one of the world's top scuba diving sites.",
  bo: "Bolivia has two capital cities: Sucre (constitutional) and La Paz (seat of government), and sits on Lake Titicaca — the world's highest navigable lake at 3,812 metres.",
  br: "Brazil contains about 60% of the Amazon rainforest and is home to 10% of all species on Earth — more biodiversity than any other country.",
  ca: "Canada has the world's longest coastline at 202,080 km — long enough to circle the Earth more than five times — and more lakes than the rest of the world combined.",
  cl: "Chile's Atacama Desert is the driest non-polar desert on Earth; some weather stations there have never recorded a single drop of rain.",
  co: "Colombia is the only South American country with coastlines on both the Pacific Ocean and the Caribbean Sea, and is the world's top producer of emeralds.",
  cr: "Costa Rica abolished its military in 1949 — one of only a handful of countries in the world with no standing army — and redirects that budget to education and healthcare.",
  cu: "Cuba has a 99.8% literacy rate and produces world-renowned cigars, hand-rolled using techniques that have been UNESCO-recognised since 2012.",
  dm: "Dominica is known as the 'Nature Isle of the Caribbean' and has 365 rivers — one for every day of the year — flowing through its volcanic landscape.",
  do: "The Dominican Republic is home to Pico Duarte at 3,098 metres — the highest peak in the entire Caribbean.",
  ec: "Ecuador was the first country in the world to grant constitutional rights to nature in 2008, legally recognising rivers, forests, and ecosystems as rights-holders.",
  sv: "El Salvador was the first country in the world to adopt Bitcoin as legal tender, in 2021, alongside the US dollar.",
  gd: "Grenada is called the 'Spice Isle' — it's the world's second-largest exporter of nutmeg, after Indonesia, and the spice even appears on its flag.",
  gt: "Guatemala has over 30 volcanoes, including Tajumulco at 4,220 metres — the highest peak in all of Central America.",
  gy: "Guyana is the only English-speaking country in South America, and nearly 90% of its population lives on a narrow coastal strip that makes up just 10% of the land.",
  ht: "Haiti was the first Black republic in the world and the first Caribbean nation to gain independence, in 1804, after a successful slave revolution against French rule.",
  hn: "Honduras is home to Copán — one of the most architecturally sophisticated cities of the ancient Maya, famous for its intricate stone hieroglyphic stairway.",
  jm: "Jamaica is the birthplace of reggae music and Bob Marley, and its Blue Mountain coffee is regularly ranked among the most expensive in the world.",
  mx: "Mexico's Great Pyramid of Cholula is the largest pyramid by volume on Earth — larger than Egypt's Great Pyramid of Giza — though much of it looks like a natural hill.",
  ni: "Nicaragua is the largest country in Central America and is nicknamed the 'Land of Lakes and Volcanoes,' with over 40 volcanoes, six of them active.",
  pa: "The Panama Canal saves ships from sailing around South America — a detour of over 22,000 km — and took over 75 million man-hours to build.",
  py: "Paraguay's flag is one of the very few in the world with a different emblem on each side — the State Coat of Arms on the front and the Treasury Seal on the back.",
  pe: "Peru's Machu Picchu sits at 2,430 metres above sea level and was built by the Inca Empire in the 15th century — then abandoned and hidden from the outside world for centuries.",
  kn: "Saint Kitts and Nevis is the smallest sovereign state in the Americas by both area and population, and was one of the first Caribbean islands colonised by Europeans, in 1623.",
  lc: "Saint Lucia's twin volcanic peaks — the Pitons — are a UNESCO World Heritage Site and rise dramatically from the sea to heights of 743 and 798 metres.",
  vc: "Saint Vincent's La Soufrière volcano erupted in April 2021 for the first time in 42 years, forcing 20,000 people to evacuate and covering the island in ash.",
  sr: "Suriname is the smallest country in South America by area, the only Dutch-speaking nation in the Americas, and has rainforest covering over 90% of its land.",
  tt: "Trinidad and Tobago is the birthplace of calypso, soca, and steelpan music — and steelband is the only acoustic musical instrument invented in the 20th century.",
  us: "The United States has the world's largest economy, 63 national parks, and spends more on its military than the next 10 countries combined.",
  uy: "Uruguay was the first country to fully legalise and regulate marijuana (2013), and is the only country to provide every schoolchild with a free laptop.",
  ve: "Venezuela is home to Angel Falls — at 979 metres, it is the world's highest uninterrupted waterfall, nearly 15 times taller than Niagara Falls.",

  // ── Asia ──────────────────────────────────────────────────────────
  af: "A 6,000-year-old wine jar was discovered in Afghanistan — some of the world's oldest evidence of wine production.",
  am: "Armenia has the world's oldest winery, found in a cave called Areni-1, dating back over 6,100 years — predating Egyptian pharaohs.",
  az: "Azerbaijan is known as the 'Land of Fire' — natural gas seeping from the ground has fuelled fires that have burned for thousands of years, some still burning today.",
  bh: "Bahrain's name means 'Two Seas' in Arabic, referring to the freshwater springs that bubble up through the salty seabed — a phenomenon that astonished ancient mariners.",
  bd: "Bangladesh is one of the world's most densely populated countries — 170 million people in an area smaller than the state of Iowa — and is the world's largest delta nation.",
  bt: "Bhutan is the world's only carbon-negative country — its forests absorb three times more CO₂ than the country produces. It also measures success by 'Gross National Happiness.'",
  bn: "Brunei's Sultan Hassanal Bolkiah owns one of the world's largest private car collections — over 7,000 vehicles, including hundreds of Ferraris and Rolls-Royces.",
  kh: "Angkor Wat in Cambodia is the largest religious monument ever constructed on Earth, covering over 400 km² — larger than the entire city of Paris.",
  cn: "China invented paper, printing, gunpowder, and the compass — four inventions that fundamentally changed the course of human civilisation.",
  cy: "According to Greek mythology, Cyprus is the birthplace of Aphrodite, the goddess of love. The island is divided between Greek Cypriot and Turkish Cypriot communities.",
  ge: "Georgia is one of the world's oldest wine-producing regions, with evidence of winemaking dating back 8,000 years — predating even ancient Egypt.",
  in: "India is the world's largest democracy with 1.4 billion people, has 22 officially recognised languages, and invented zero and the decimal system.",
  id: "Indonesia is the world's largest archipelago nation with over 17,000 islands, the world's fourth-most-populous country, and home to the largest flower on Earth — the Rafflesia.",
  ir: "Iran (ancient Persia) was the world's first superpower under Cyrus the Great in 550 BC — the Persian Empire was the largest empire in ancient history.",
  iq: "Iraq is home to Mesopotamia — the 'Cradle of Civilisation' — where writing, the wheel, agriculture, and urban cities were all invented over 5,000 years ago.",
  il: "Israel leads the world in scientists per capita and start-ups per capita (nicknamed 'Start-up Nation'). The Dead Sea shoreline is the lowest point on Earth at −430 metres.",
  jp: "Japan has had an unbroken imperial dynasty for over 2,600 years — the world's oldest continuous hereditary monarchy — and has more vending machines per person than any country.",
  jo: "Jordan's Petra — the ancient rose-red city carved entirely into cliff faces — was one of the world's most spectacular cities in 300 BC and is one of the New Seven Wonders.",
  kz: "Kazakhstan is the world's largest landlocked country, spanning two continents. The world's first space launch site — the Baikonur Cosmodrome — is located here.",
  kw: "Kuwait's oil reserves, though its territory is tiny, represent about 6% of the world's total proven crude oil reserves.",
  kg: "Kyrgyzstan's traditional felt tent — the yurt — is a UNESCO Intangible Heritage and still the primary home for many of the country's nomadic herders.",
  la: "Laos is the most heavily bombed country per capita in history — the US dropped more than 2 million tonnes of bombs during the Vietnam War era, many still unexploded today.",
  lb: "Lebanon's Byblos is one of the world's oldest continuously inhabited cities, dating back over 7,000 years, and gave its name to the Greek word for 'book' (biblos).",
  my: "Malaysia is split across two separate landmasses separated by 640 km of the South China Sea — Peninsular Malaysia and Malaysian Borneo.",
  mv: "The Maldives is the world's lowest-lying country, with an average ground level of just 1.5 metres above sea level, making it one of the most vulnerable to climate change.",
  mn: "Mongolia is the world's most sparsely populated country with just 2 people per km². Genghis Khan built the largest contiguous land empire in history from here in the 13th century.",
  mm: "Myanmar's Shwedagon Pagoda is covered in 60 tonnes of gold and decorated with 5,500 diamonds — one of the most sacred Buddhist sites on Earth.",
  np: "Nepal is home to 8 of the world's 10 highest mountain peaks, including Everest, and is the only country in the world with a non-rectangular national flag.",
  kp: "North Korea is one of the world's most isolated countries — it has its own time zone (30 minutes behind South Korea) and its citizens cannot freely leave.",
  om: "Oman's ancient frankincense trade routes were so important they became a UNESCO World Heritage Site. Oman once controlled the global frankincense supply.",
  pk: "Pakistan is home to K2 — the world's second-highest mountain — and has more glaciers outside the polar regions than any other country on Earth.",
  ps: "The city of Jericho, within Palestinian territory, is considered one of the oldest continuously inhabited cities on Earth, with settlements dating back over 10,000 years.",
  ph: "The Philippines is an archipelago of over 7,600 islands, the world's leading producer of coconuts, and has the highest concentration of unique mammal species on any island group.",
  qa: "Qatar has the world's highest GDP per capita and hosted the 2022 FIFA World Cup — the first ever held in the Middle East and the first played in November-December.",
  sa: "Saudi Arabia is home to Mecca — the holiest city in Islam — and holds the world's second-largest proven oil reserves. It was the last country to allow women to drive (2018).",
  sg: "Singapore is one of only three city-states in the world, has zero natural resources, yet boasts one of the world's highest living standards and busiest ports.",
  kr: "South Korea went from one of the world's poorest countries after the Korean War (1950-53) to one of the richest in just 60 years — an achievement called the 'Miracle on the Han River.'",
  lk: "Sri Lanka produces about 23% of the world's tea supply and was one of the first countries in the modern world to elect a female prime minister — Sirimavo Bandaranaike in 1960.",
  sy: "Syria's capital Damascus is one of the oldest continuously inhabited cities in the world, with evidence of settlement dating back at least 11,000 years.",
  tw: "Taiwan produces over 60% of the world's semiconductors through TSMC — the chips that power everything from smartphones to fighter jets.",
  tj: "Tajikistan is over 93% mountainous — it has the Pamir Mountains, known as the 'Roof of the World,' with peaks exceeding 7,000 metres.",
  th: "Thailand is the only Southeast Asian country that was never colonised by a European power — its name even means 'Land of the Free' in Thai.",
  tl: "Timor-Leste (East Timor) is one of the world's youngest countries, achieving independence in 2002, and has some of the most biodiverse coral reefs on Earth.",
  tr: "Istanbul is the only city in the world located on two continents — Europe and Asia — and it was the capital of three major empires: Roman, Byzantine, and Ottoman.",
  tm: "Turkmenistan's 'Door to Hell' — the Darvaza gas crater — has been burning continuously since Soviet geologists accidentally ignited it in 1971.",
  ae: "The UAE's Burj Khalifa stands 828 metres tall — the world's tallest building — and its observation deck is so high that you can watch the sunset twice in one day.",
  uz: "Uzbekistan is one of only two doubly landlocked countries in the world (surrounded entirely by other landlocked countries). Its Silk Road cities of Samarkand and Bukhara are over 2,500 years old.",
  vn: "Vietnam is the world's second-largest coffee exporter and Ha Long Bay — with over 1,600 limestone islands rising from the sea — is one of the world's most dramatic seascapes.",
  ye: "Yemen's island of Socotra is so isolated that a third of its plant species exist nowhere else on Earth — including the famous Dragon Blood Tree with its umbrella-shaped canopy.",

  // ── Europe ────────────────────────────────────────────────────────
  al: "During communist rule, Albania's dictator Enver Hoxha built over 750,000 concrete bunkers across the country — one for approximately every four citizens.",
  ad: "Andorra has no airport, no army, and no income tax. Nestled in the Pyrenees between France and Spain, it has one of the world's highest life expectancies.",
  at: "Austria is the birthplace of Mozart, the home of Beethoven, and where Sigmund Freud developed psychoanalysis. Vienna has been ranked the world's most livable city multiple times.",
  by: "Belarus is home to the Białowieża Forest — the last primeval forest in Europe, shared with Poland — where wild European bison (wisent) roam free.",
  be: "Belgium is home to the headquarters of both NATO and the European Union, and produces over 220,000 tonnes of chocolate every year.",
  ba: "Sarajevo, Bosnia's capital, is where Archduke Franz Ferdinand was assassinated in 1914 — the event that directly triggered the start of World War I.",
  bg: "Bulgaria is home to the Varna Gold Treasure — the world's oldest processed gold artefacts, dating back over 6,500 years and discovered in a necropolis in 1972.",
  hr: "Croatia has over 1,244 islands along its Adriatic coastline and is the birthplace of the necktie — the word 'cravat' comes from 'Croat.'",
  cz: "Prague Castle is the world's largest ancient castle complex by area, covering about 70,000 m² — and Czechs drink more beer per capita than any other nation on Earth.",
  dk: "Denmark is home to the world's oldest continuously operating amusement park (Bakken, 1583), invented LEGO, and has had the same royal family since the 10th century.",
  ee: "Estonia is one of the world's most digitally advanced countries — you can vote, file taxes, register a company, and even get married entirely online.",
  fi: "Finland has about 188,000 lakes and 98,000 islands, and has been ranked the world's happiest country multiple years running by the UN World Happiness Report.",
  fr: "France is the world's most visited country with nearly 90 million tourists per year. The Eiffel Tower was originally built as a temporary structure and nearly demolished in 1909.",
  de: "Germany is home to over 1,500 different types of beer and the printing press — invented by Johannes Gutenberg around 1440 — which revolutionised the spread of knowledge.",
  gr: "Greece is the birthplace of democracy, the Olympic Games, Western philosophy, and the theatre — and has more archaeological museums than any other country in the world.",
  hu: "Budapest sits atop the world's largest thermal water cave system, with over 100 hot springs — the city has been a spa destination since Roman times.",
  is: "Iceland has no mosquitoes (the climate is too harsh), no army, a 99% literacy rate, and gets 100% of its electricity from renewable energy.",
  ie: "Ireland is the only country in the world whose national symbol (the harp) is a musical instrument. It has produced four Nobel Laureates in Literature.",
  it: "Italy has more UNESCO World Heritage Sites than any other country — 58 as of 2024 — and is home to Europe's only active mainland volcano, Vesuvius.",
  xk: "Kosovo declared independence in 2008 and has the youngest population in Europe — over half its citizens are under 25 years old.",
  lv: "Riga, Latvia, is home to the largest collection of Art Nouveau architecture in the world, and Latvia was possibly the first country to use a Christmas tree for public celebrations — in 1510.",
  li: "Liechtenstein is one of only two doubly landlocked countries in the world, has no airport, no army, and surprisingly is the world's leading exporter of false teeth.",
  lt: "Lithuania was the last country in Europe to convert to Christianity — in 1387 — and was also the first Soviet republic to declare independence, in 1990.",
  lu: "Luxembourg is the world's only Grand Duchy and consistently has the highest GDP per capita of any country in the world.",
  mt: "Malta's Megalithic Temples are among the world's oldest free-standing structures — built over 5,000 years ago, predating Stonehenge and the Egyptian pyramids.",
  md: "Moldova has the world's largest wine cellar — the Milestii Mici winery holds 1.5 million bottles in 200 km of underground tunnels.",
  mc: "Monaco is the world's most densely populated country and is smaller than New York's Central Park — yet it has the world's highest concentration of millionaires.",
  me: "Montenegro's name literally means 'Black Mountain,' and the Tara River Canyon is the deepest canyon in Europe and the second-deepest in the world.",
  nl: "More than a quarter of the Netherlands is below sea level. It's the world's second-largest exporter of food and agricultural products, after only the USA.",
  mk: "Mother Teresa was born Anjezë Gonxhe Bojaxhiu in Skopje, North Macedonia, in 1910. Lake Ohrid in the country is one of Europe's oldest lakes, estimated at 3–5 million years old.",
  no: "Norway's Leif Erikson reached North America around 1000 AD — roughly 500 years before Columbus. Norway also invented the cheese slicer and the aerosol can.",
  pl: "Poland is the birthplace of Copernicus, Frédéric Chopin, and Marie Curie — and the University of Kraków admitted women as early as 1897.",
  pt: "Portugal is the world's oldest nation-state with essentially unchanged borders since 1139, and its explorers opened sea routes to Africa, India, and the Americas.",
  ro: "Romania's Bran Castle inspired Bram Stoker's Dracula legend, and Bucharest's Bulevardul Unirii is the widest central boulevard in Europe.",
  ru: "Russia spans 11 time zones — from Kaliningrad near Poland to Chukotka near Alaska — and Lake Baikal holds 20% of the world's unfrozen fresh surface water.",
  sm: "San Marino is the world's oldest republic, founded in 301 AD, and claims to be the first country Napoleon promised not to invade — out of respect for its freedom.",
  rs: "Serbia is the birthplace of Nikola Tesla, one of history's greatest inventors, who pioneered alternating current electricity that powers most of the world today.",
  sk: "Slovakia has the highest density of castles and chateaux per capita in the world — over 100 castle ruins dot the countryside.",
  si: "Slovenia is one of Europe's greenest countries, with over 60% of its land covered by forest, and is the source of the Sava, Drava, and Soča rivers.",
  es: "Spain's La Tomatina festival sees 150,000 tomatoes hurled in a single hour, and the Camino de Santiago pilgrimage route has been walked for over 1,000 years.",
  se: "Sweden invented the pacemaker, dynamite (Alfred Nobel, who funded the Nobel Prize), the zipper, and Bluetooth technology — named after a Viking king, Harald Bluetooth.",
  ch: "Switzerland has been officially neutral since 1815 and has never fought in a war since. It's home to the Red Cross, founded in Geneva in 1863.",
  ua: "Ukraine is Europe's largest country by area (excluding Russia) and is the world's largest sunflower oil exporter and second-largest wheat exporter.",
  gb: "The United Kingdom opened the world's first underground railway (the London Underground) in 1863, and its monarchy is the world's oldest constitutional monarchy still in operation.",
  va: "Vatican City is the world's smallest country at just 0.44 km², home to the Pope, and Michelangelo spent four years painting the Sistine Chapel ceiling while lying on his back.",

  // ── Oceania ───────────────────────────────────────────────────────
  au: "Australia is home to 21 of the world's 25 most venomous snakes, yet statistically you are far more likely to be killed by a bee sting or a kangaroo than a snakebite.",
  fj: "Fiji consists of 333 islands and is considered the 'soft coral capital of the world' — its reefs have some of the most chemically complex coral ecosystems on Earth.",
  ki: "Kiribati is the first country to welcome the New Year (in the UTC+14 time zone) and may be the first to disappear as rising seas threaten its low-lying atolls.",
  mh: "The Marshall Islands was the site of 67 US nuclear weapons tests between 1946 and 1958 — including the first hydrogen bomb test — leaving lasting environmental damage.",
  fm: "Micronesia's 607 islands are scattered across an ocean area larger than the continental United States, yet only four island groups make up the country.",
  nr: "Nauru was once the richest country per capita in the world, thanks to phosphate mining, but the deposits ran out and left 80% unemployment and a landscape of barren rock.",
  nz: "New Zealand was the first country in the world to give women the right to vote, in 1893, and was one of the last places on Earth settled by humans — only around 1250-1300 AD.",
  pw: "Palau's Jellyfish Lake is home to millions of golden jellyfish that have evolved to be completely stingless, allowing swimmers to float freely among them.",
  pg: "Papua New Guinea is one of the world's most linguistically diverse countries, with over 800 languages spoken — about 12% of all languages on Earth.",
  ws: "Samoa moved the international date line in 2011 to align with Australia, skipping Friday 30 December entirely — the entire calendar day simply did not exist in Samoa.",
  sb: "The Solomon Islands' waters contain hundreds of World War II shipwrecks and aircraft from the 1942-43 Guadalcanal Campaign, making it one of the world's top wreck-diving destinations.",
  to: "Tonga is the only Pacific Island nation never formally colonised by a foreign power, and it remains an absolute monarchy — one of the last in the world.",
  tv: "Tuvalu earns millions of dollars each year simply by leasing its internet country code — .tv — to television companies and streaming platforms around the world.",
  vu: "Vanuatu's Mount Yasur on Tanna Island is one of the world's most accessible active volcanoes — you can walk to its rim and peer down into the glowing lava.",
};
