// Bordering countries (land borders only, by ISO alpha-2 code)
export const COUNTRY_BORDERS: Record<string, string[]> = {
  // ── Africa ────────────────────────────────────────────────────────
  dz: ['tn','ly','ne','ml','mr','ma'],
  ao: ['cd','cg','zm','na'],
  bj: ['ng','ne','bf','tg'],
  bw: ['za','zw','zm','na'],
  bf: ['ml','ne','bj','tg','gh','ci'],
  bi: ['cd','rw','tz'],
  cm: ['ng','td','cf','cg','ga','gq'],
  cf: ['sd','ss','cd','cg','cm','td'],
  td: ['ly','sd','cf','cm','ne','ng'],
  cg: ['ga','cm','cf','cd','ao'],
  cd: ['cg','cf','ss','ug','rw','bi','tz','zm','ao'],
  dj: ['er','et','so'],
  eg: ['ly','sd','il','ps'],
  gq: ['cm','ga'],
  er: ['et','sd','dj'],
  sz: ['za','mz'],
  et: ['er','dj','so','ke','ss','sd'],
  ga: ['cm','gq','cg'],
  gm: ['sn'],
  gh: ['ci','bf','tg'],
  gn: ['sn','ml','ci','lr','sl','gw'],
  gw: ['sn','gn'],
  ci: ['ml','bf','gh','lr','gn'],
  ke: ['et','ss','ug','tz','so'],
  ls: ['za'],
  lr: ['gn','ci','sl'],
  ly: ['tn','eg','sd','td','ne','dz'],
  mw: ['tz','zm','mz'],
  ml: ['dz','ne','bf','ci','gn','sn','mr'],
  mr: ['sn','ml','dz'],
  ma: ['dz'],
  mz: ['tz','mw','zm','zw','za','sz'],
  na: ['za','bw','zm','ao'],
  ne: ['dz','ly','td','ng','bj','bf','ml'],
  ng: ['ne','td','cm','bj'],
  rw: ['ug','tz','bi','cd'],
  sn: ['mr','ml','gn','gw','gm'],
  sl: ['gn','lr'],
  so: ['et','dj','ke'],
  za: ['na','bw','zw','mz','sz','ls'],
  ss: ['sd','et','ke','ug','cd','cf'],
  sd: ['eg','ly','td','cf','ss','et','er'],
  tz: ['ke','ug','rw','bi','cd','zm','mw','mz'],
  tg: ['gh','bj','bf'],
  tn: ['dz','ly'],
  ug: ['ss','ke','tz','rw','cd'],
  zm: ['cd','tz','mw','mz','zw','bw','na','ao'],
  zw: ['zm','mz','za','bw'],

  // ── Americas ──────────────────────────────────────────────────────
  ar: ['bo','br','cl','py','uy'],
  bz: ['mx','gt'],
  bo: ['ar','br','cl','pe','py'],
  br: ['ar','bo','co','gy','py','pe','sr','uy','ve'],
  ca: ['us'],
  cl: ['ar','bo','pe'],
  co: ['br','ec','pe','ve','pa'],
  cr: ['ni','pa'],
  do: ['ht'],
  ec: ['co','pe'],
  sv: ['gt','hn'],
  gt: ['mx','bz','hn','sv'],
  gy: ['br','sr','ve'],
  ht: ['do'],
  hn: ['gt','sv','ni'],
  mx: ['us','gt','bz'],
  ni: ['hn','cr'],
  pa: ['cr','co'],
  py: ['ar','bo','br'],
  pe: ['bo','br','cl','co','ec'],
  sr: ['br','gy'],
  us: ['ca','mx'],
  uy: ['ar','br'],
  ve: ['br','co','gy'],

  // ── Asia ──────────────────────────────────────────────────────────
  af: ['cn','ir','pk','tj','tm','uz'],
  am: ['az','ge','ir','tr'],
  az: ['am','ge','ir','ru','tr'],
  bd: ['in','mm'],
  bt: ['cn','in'],
  bn: ['my'],
  kh: ['la','th','vn'],
  cn: ['af','bt','in','kz','kg','la','mn','mm','np','pk','ru','tj','vn'],
  ge: ['am','az','ru','tr'],
  in: ['bd','bt','cn','mm','np','pk'],
  id: ['pg','tl','my'],
  ir: ['af','am','az','iq','pk','tr','tm'],
  iq: ['ir','jo','kw','sa','sy','tr'],
  il: ['eg','jo','lb','sy','ps'],
  jo: ['il','iq','sa','sy','ps'],
  kz: ['cn','kg','ru','tm','uz'],
  kw: ['iq','sa'],
  kg: ['cn','kz','tj','uz'],
  la: ['cn','kh','mm','th','vn'],
  lb: ['il','sy'],
  my: ['bn','id','th'],
  mn: ['cn','ru'],
  mm: ['bd','cn','in','la','th'],
  np: ['cn','in'],
  kp: ['cn','kr','ru'],
  om: ['sa','ae','ye'],
  pk: ['af','cn','in','ir'],
  ps: ['eg','il','jo'],
  qa: ['sa'],
  sa: ['iq','jo','kw','om','qa','ae','ye'],
  sg: ['my'],
  kr: ['kp'],
  lk: [],
  sy: ['il','iq','jo','lb','tr'],
  tj: ['af','cn','kg','uz'],
  th: ['kh','la','my','mm'],
  tl: ['id'],
  tr: ['am','az','bg','ge','gr','iq','ir','sy'],
  tm: ['af','ir','kz','uz'],
  ae: ['om','sa'],
  uz: ['af','kz','kg','tj','tm'],
  vn: ['cn','kh','la'],
  ye: ['om','sa'],

  // ── Europe ────────────────────────────────────────────────────────
  al: ['gr','mk','xk','me'],
  ad: ['fr','es'],
  at: ['ch','cz','de','hu','it','li','sk','si'],
  by: ['lv','lt','pl','ru','ua'],
  be: ['fr','de','lu','nl'],
  ba: ['hr','me','rs'],
  bg: ['gr','mk','ro','rs','tr'],
  hr: ['ba','hu','me','rs','si'],
  cz: ['at','de','pl','sk'],
  dk: ['de'],
  ee: ['lv','ru'],
  fi: ['no','ru','se'],
  fr: ['ad','be','de','it','lu','mc','es','ch'],
  de: ['at','be','cz','dk','fr','lu','nl','pl','ch'],
  gr: ['al','bg','mk','tr'],
  hu: ['at','hr','ro','rs','sk','si','ua'],
  ie: ['gb'],
  it: ['at','fr','sm','si','ch','va'],
  xk: ['al','mk','me','rs'],
  lv: ['by','ee','lt','ru'],
  li: ['at','ch'],
  lt: ['by','lv','pl','ru'],
  lu: ['be','fr','de'],
  md: ['ro','ua'],
  mc: ['fr'],
  me: ['al','ba','hr','rs','xk'],
  nl: ['be','de'],
  mk: ['al','bg','gr','xk','rs'],
  no: ['fi','ru','se'],
  pl: ['by','cz','de','lt','ru','sk','ua'],
  pt: ['es'],
  ro: ['bg','hu','md','rs','ua'],
  ru: ['az','by','cn','ee','fi','ge','kz','lv','lt','mn','no','kp','pl','ua'],
  sm: ['it'],
  rs: ['al','ba','bg','hr','hu','xk','mk','me','ro'],
  sk: ['at','cz','hu','pl','ua'],
  si: ['at','hr','hu','it'],
  es: ['ad','fr','pt'],
  se: ['fi','no'],
  ch: ['at','fr','de','it','li'],
  ua: ['by','hu','md','pl','ro','ru','sk'],
  gb: ['ie'],
  va: ['it'],

  // ── Oceania ───────────────────────────────────────────────────────
  pg: ['id'],

  // Islands — no land borders
  ag:[], bb:[], bs:[], cv:[], km:[], cu:[], cy:[], dm:[],
  fj:[], gd:[], is:[], jp:[], ki:[], kn:[], lc:[],
  mg:[], mv:[], mh:[], mt:[], mu:[], nr:[], nz:[], fm:[],
  pw:[], ph:[], ws:[], sc:[], sb:[], st:[], to:[], tt:[], tv:[], vc:[],
};

// UN-inspired sub-regions for geographic hints
export const COUNTRY_SUBREGION: Record<string, string> = {
  // ── Northern Africa ────────────────────────────────────────────────
  dz: 'Northern Africa', eg: 'Northern Africa', ly: 'Northern Africa',
  ma: 'Northern Africa', sd: 'Northern Africa', tn: 'Northern Africa',

  // ── West Africa ───────────────────────────────────────────────────
  bj: 'West Africa', bf: 'West Africa', cv: 'West Africa', ci: 'West Africa',
  gm: 'West Africa', gh: 'West Africa', gn: 'West Africa', gw: 'West Africa',
  lr: 'West Africa', ml: 'West Africa', mr: 'West Africa', ne: 'West Africa',
  ng: 'West Africa', sn: 'West Africa', sl: 'West Africa', tg: 'West Africa',

  // ── Central Africa ────────────────────────────────────────────────
  ao: 'Central Africa', cm: 'Central Africa', cf: 'Central Africa',
  td: 'Central Africa', cg: 'Central Africa', cd: 'Central Africa',
  gq: 'Central Africa', ga: 'Central Africa', st: 'Central Africa',

  // ── East Africa ───────────────────────────────────────────────────
  bi: 'East Africa', dj: 'East Africa', er: 'East Africa', et: 'East Africa',
  ke: 'East Africa', mg: 'East Africa', mw: 'East Africa', mu: 'East Africa',
  mz: 'East Africa', rw: 'East Africa', sc: 'East Africa', so: 'East Africa',
  ss: 'East Africa', tz: 'East Africa', ug: 'East Africa', zm: 'East Africa',
  zw: 'East Africa',

  // ── Southern Africa ───────────────────────────────────────────────
  bw: 'Southern Africa', ls: 'Southern Africa', na: 'Southern Africa',
  za: 'Southern Africa', sz: 'Southern Africa',

  // ── North America ─────────────────────────────────────────────────
  ca: 'North America', mx: 'North America', us: 'North America',

  // ── Central America ───────────────────────────────────────────────
  bz: 'Central America', cr: 'Central America', sv: 'Central America',
  gt: 'Central America', hn: 'Central America', ni: 'Central America',
  pa: 'Central America',

  // ── Caribbean ─────────────────────────────────────────────────────
  ag: 'Caribbean', bs: 'Caribbean', bb: 'Caribbean', cu: 'Caribbean',
  dm: 'Caribbean', do: 'Caribbean', gd: 'Caribbean', ht: 'Caribbean',
  jm: 'Caribbean', kn: 'Caribbean', lc: 'Caribbean', tt: 'Caribbean',
  vc: 'Caribbean',

  // ── South America ─────────────────────────────────────────────────
  ar: 'South America', bo: 'South America', br: 'South America',
  cl: 'South America', co: 'South America', ec: 'South America',
  gy: 'South America', py: 'South America', pe: 'South America',
  sr: 'South America', uy: 'South America', ve: 'South America',

  // ── Central Asia ──────────────────────────────────────────────────
  kz: 'Central Asia', kg: 'Central Asia', tj: 'Central Asia',
  tm: 'Central Asia', uz: 'Central Asia',

  // ── East Asia ─────────────────────────────────────────────────────
  cn: 'East Asia', jp: 'East Asia', kp: 'East Asia',
  kr: 'East Asia', mn: 'East Asia', tw: 'East Asia',

  // ── Southeast Asia ────────────────────────────────────────────────
  bn: 'Southeast Asia', kh: 'Southeast Asia', id: 'Southeast Asia',
  la: 'Southeast Asia', my: 'Southeast Asia', mm: 'Southeast Asia',
  ph: 'Southeast Asia', sg: 'Southeast Asia', tl: 'Southeast Asia',
  th: 'Southeast Asia', vn: 'Southeast Asia',

  // ── South Asia ────────────────────────────────────────────────────
  af: 'South Asia', bd: 'South Asia', bt: 'South Asia', in: 'South Asia',
  mv: 'South Asia', np: 'South Asia', pk: 'South Asia', lk: 'South Asia',

  // ── Western Asia / Middle East ────────────────────────────────────
  am: 'Western Asia', az: 'Western Asia', bh: 'Western Asia',
  ge: 'Western Asia', ir: 'Western Asia',
  iq: 'Western Asia', il: 'Western Asia', jo: 'Western Asia',
  kw: 'Western Asia', lb: 'Western Asia', om: 'Western Asia',
  ps: 'Western Asia', qa: 'Western Asia', sa: 'Western Asia',
  sy: 'Western Asia', tr: 'Western Asia', ae: 'Western Asia',
  ye: 'Western Asia',

  // ── Northern Europe ───────────────────────────────────────────────
  dk: 'Northern Europe', ee: 'Northern Europe', fi: 'Northern Europe',
  is: 'Northern Europe', lv: 'Northern Europe', lt: 'Northern Europe',
  no: 'Northern Europe', se: 'Northern Europe', gb: 'Northern Europe',
  ie: 'Northern Europe',

  // ── Western Europe ────────────────────────────────────────────────
  at: 'Western Europe', be: 'Western Europe', fr: 'Western Europe',
  de: 'Western Europe', li: 'Western Europe', lu: 'Western Europe',
  mc: 'Western Europe', nl: 'Western Europe', ch: 'Western Europe',

  // ── Southern Europe ───────────────────────────────────────────────
  al: 'Southern Europe', ad: 'Southern Europe', ba: 'Southern Europe',
  hr: 'Southern Europe', cy: 'Southern Europe', gr: 'Southern Europe',
  it: 'Southern Europe', xk: 'Southern Europe', mt: 'Southern Europe',
  me: 'Southern Europe', pt: 'Southern Europe', sm: 'Southern Europe',
  rs: 'Southern Europe', si: 'Southern Europe', es: 'Southern Europe',
  mk: 'Southern Europe', va: 'Southern Europe',

  // ── Eastern Europe ────────────────────────────────────────────────
  by: 'Eastern Europe', bg: 'Eastern Europe', cz: 'Eastern Europe',
  hu: 'Eastern Europe', md: 'Eastern Europe', pl: 'Eastern Europe',
  ro: 'Eastern Europe', ru: 'Eastern Europe', sk: 'Eastern Europe',
  ua: 'Eastern Europe',

  // ── Oceania ───────────────────────────────────────────────────────
  au: 'Oceania (Australia)', nz: 'Oceania (New Zealand)',
  fj: 'Melanesia', pg: 'Melanesia', sb: 'Melanesia', vu: 'Melanesia',
  fm: 'Micronesia', ki: 'Micronesia', mh: 'Micronesia',
  nr: 'Micronesia', pw: 'Micronesia',
  ws: 'Polynesia', to: 'Polynesia', tv: 'Polynesia',
};
